function printer0() { openOverlay("0"); }
function printer1() { openOverlay("1"); }
function printer2() { openOverlay("2"); }
function printer3() { openOverlay("3"); }
function printer4() { openOverlay("4"); }
function printer5() { openOverlay("5"); }
function printer6() { openOverlay("6"); }
function printer7() { openOverlay("7"); }
function printer8() { openOverlay("8"); }
function printer9() { openOverlay("9"); }
function printer10() { openOverlay("10"); }
function printer11() { openOverlay("11"); }
function printer12() { openOverlay("12"); }
function printer13() { openOverlay("13"); }
function printer14() { openOverlay("14"); }